apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-optimizer.fullname" . }}
  labels:
    {{- include "karpenter-optimizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.frontend.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: http-frontend
      protocol: TCP
      name: http
    - port: {{ .Values.service.backendPort | default .Values.config.port }}
      targetPort: http
      protocol: TCP
      name: http-backend
    {{- else }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "karpenter-optimizer.selectorLabels" . | nindent 4 }}

