apiVersion: v2
name: karpenter-optimizer
description: A Helm chart for Karpenter Optimizer - Cost optimization tool for Karpenter NodePools
type: application
version: 0.0.15
appVersion: "0.0.15"
keywords:
  - karpenter
  - kubernetes
  - cost-optimization
  - aws
  - ec2
home: https://github.com/kaskol10/karpenter-optimizer
sources:
  - https://github.com/kaskol10/karpenter-optimizer
icon: https://raw.githubusercontent.com/kaskol10/karpenter-optimizer/main/docs/logo.png

